#!/usr/bin/env bash

check_distro(){
	output_distro=$(grep '^NAME' /etc/os-release | cut -d "=" -f 2 | cut -d "\"" -f 2)
    case $output_distro in
        "Ubuntu")
            echo "Ubuntu distro"
            ;;
        
        "Fedora")
            echo "Fedora distro"
            ;;

        *)
            echo "Distro not compatible"
            ;;
    esac
}